name: Docker Build / Test / Push

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set IMAGE_TAG env
      id: vars
      run: echo "TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/2025cloud:${{ steps.vars.outputs.TAG }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/2025cloud:${{ steps.vars.outputs.TAG }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/2025cloud:${{ steps.vars.outputs.TAG }} ${{ secrets.DOCKER_USERNAME }}/2025cloud:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/2025cloud:latest
